"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import {
  Calendar,
  CheckCircle2,
  ChevronRight,
  Cpu,
  FileText,
  Plus,
  Radio,
  Search,
  User,
  Zap,
} from "lucide-react";
import axiosInstance from "@/lib/axios";
import { FastF1LoadingSkeleton } from "@/components/race-engineer/FastF1LoadingSkeleton";

interface EngineeringReport {
  report_id: string;
  team_id?: string;
  generated_by: string;
  generator_name: string;
  report_type: string;
  created_at: string;
  data: {
    session_id?: string;
    driver_code?: string;
    driver_name?: string;
    lap_numbers?: number[];
    key_findings?: string;
    stint_degradation_trend?: string;
    summary_stats?: Record<string, any>;
  };
}

async function fetchEngineeringReports(): Promise<EngineeringReport[]> {
  const res = await axiosInstance.get("/api/v1/race-engineer/reports");
  return res.data;
}

export default function EngineeringReportsPage() {
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedReport, setSelectedReport] = useState<EngineeringReport | null>(null);

  const { data: reports, isLoading, isError, refetch } = useQuery<EngineeringReport[]>({
    queryKey: ["engineeringReports"],
    queryFn: fetchEngineeringReports,
    staleTime: 60 * 1000,
  });

  const filteredReports = (reports || []).filter((r) => {
    const sId = r.data?.session_id || "";
    const dName = r.data?.driver_name || r.data?.driver_code || "";
    const findings = r.data?.key_findings || "";
    const q = searchTerm.toLowerCase();
    return (
      sId.toLowerCase().includes(q) ||
      dName.toLowerCase().includes(q) ||
      findings.toLowerCase().includes(q)
    );
  });

  if (isLoading) {
    return <FastF1LoadingSkeleton title="Loading Engineering Reports" message="Fetching past telemetry report snapshots..." />;
  }

  return (
    <div className="space-y-8">
      {/* Top Banner */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 rounded-2xl border border-slate-800/80 bg-slate-900/60 p-6 backdrop-blur-md">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="inline-flex items-center gap-1.5 rounded-full bg-cyan-500/15 px-3 py-0.5 text-xs font-semibold text-cyan-300 ring-1 ring-cyan-500/30">
              <FileText size={12} className="text-cyan-400" /> Engineering Reports
            </span>
            <span className="text-xs text-slate-400">• Team Filtered Snapshots</span>
          </div>
          <h1 className="text-2xl font-bold tracking-tight text-slate-100">Engineering Performance Reports</h1>
          <p className="text-sm text-slate-400 mt-0.5">
            Archived session summaries, stint degradation trends, and driver key findings.
          </p>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
        <div className="relative w-full sm:w-80">
          <Search size={16} className="absolute left-3 top-2.5 text-slate-500" />
          <input
            type="text"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            placeholder="Search reports by session or driver..."
            className="w-full rounded-xl border border-slate-800 bg-slate-900/80 pl-9 pr-4 py-2 text-xs text-slate-100 focus:border-cyan-500 focus:outline-none"
          />
        </div>

        <span className="text-xs text-slate-400">
          Showing <strong className="text-slate-200">{filteredReports.length}</strong> reports
        </span>
      </div>

      {/* Reports DataTable */}
      <div className="rounded-xl border border-slate-800/80 bg-slate-900/60 overflow-hidden backdrop-blur-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-slate-300">
            <thead className="bg-slate-950 text-slate-400 uppercase font-semibold text-[10px] tracking-wider border-b border-slate-800">
              <tr>
                <th className="py-3.5 px-4">Report ID</th>
                <th className="py-3.5 px-4">Session ID</th>
                <th className="py-3.5 px-4">Driver</th>
                <th className="py-3.5 px-4">Generated By</th>
                <th className="py-3.5 px-4">Created Date</th>
                <th className="py-3.5 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60">
              {filteredReports.length === 0 ? (
                <tr>
                  <td colSpan={6} className="py-8 text-center text-slate-500">
                    No engineering reports found matching criteria.
                  </td>
                </tr>
              ) : (
                filteredReports.map((report) => (
                  <tr key={report.report_id} className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-3.5 px-4 font-mono font-bold text-cyan-400">
                      #{report.report_id.slice(0, 8)}
                    </td>
                    <td className="py-3.5 px-4 font-mono text-slate-200">
                      {report.data?.session_id || "Session Report"}
                    </td>
                    <td className="py-3.5 px-4 font-semibold text-slate-100">
                      {report.data?.driver_name || report.data?.driver_code || "Team Driver"}
                    </td>
                    <td className="py-3.5 px-4 text-slate-400">
                      {report.generator_name}
                    </td>
                    <td className="py-3.5 px-4 text-slate-400 font-mono">
                      {new Date(report.created_at).toLocaleDateString()}{" "}
                      {new Date(report.created_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
                    </td>
                    <td className="py-3.5 px-4 text-right">
                      <button
                        onClick={() => setSelectedReport(report)}
                        className="rounded-lg bg-cyan-500/10 px-3 py-1.5 text-xs font-semibold text-cyan-300 hover:bg-cyan-500/20 transition-colors ring-1 ring-cyan-500/20"
                      >
                        View Summary
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Report Summary Drawer/Modal */}
      {selectedReport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 backdrop-blur-sm p-4">
          <div className="w-full max-w-2xl rounded-2xl border border-slate-800 bg-slate-900 p-6 shadow-2xl space-y-6">
            <div className="flex items-center justify-between border-b border-slate-800 pb-4">
              <div>
                <span className="rounded bg-cyan-500/15 px-2.5 py-0.5 text-[10px] font-bold text-cyan-300 uppercase tracking-wide">
                  Report #{selectedReport.report_id.slice(0, 8)}
                </span>
                <h2 className="text-lg font-bold text-slate-100 mt-1">
                  Engineering Analysis: {selectedReport.data?.session_id || "F1 Session"}
                </h2>
              </div>
              <button onClick={() => setSelectedReport(null)} className="text-slate-400 hover:text-slate-200">
                ✕
              </button>
            </div>

            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4 rounded-xl bg-slate-950 p-4 border border-slate-800 text-xs">
                <div>
                  <p className="text-slate-400 font-medium">Target Driver:</p>
                  <p className="text-slate-100 font-bold text-sm mt-0.5">
                    {selectedReport.data?.driver_name || selectedReport.data?.driver_code || "Team Driver"}
                  </p>
                </div>
                <div>
                  <p className="text-slate-400 font-medium">Generated By:</p>
                  <p className="text-slate-100 font-bold text-sm mt-0.5">{selectedReport.generator_name}</p>
                </div>
              </div>

              <div>
                <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider mb-1.5">
                  Key Engineering Findings
                </h4>
                <div className="rounded-lg bg-slate-950 p-4 border border-slate-800 text-xs text-slate-200 leading-relaxed">
                  {selectedReport.data?.key_findings || "No key findings notes entered."}
                </div>
              </div>

              <div>
                <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider mb-1.5">
                  Stint Degradation Trend
                </h4>
                <div className="rounded-lg bg-slate-950 p-4 border border-slate-800 text-xs text-amber-300 leading-relaxed">
                  {selectedReport.data?.stint_degradation_trend || "Normal tire degradation observed."}
                </div>
              </div>

              {selectedReport.data?.summary_stats && (
                <div>
                  <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider mb-1.5">
                    Summary Performance Statistics
                  </h4>
                  <pre className="rounded-lg bg-slate-950 p-3 border border-slate-800 text-xs font-mono text-cyan-300 overflow-x-auto">
                    {JSON.stringify(selectedReport.data.summary_stats, null, 2)}
                  </pre>
                </div>
              )}
            </div>

            <div className="flex justify-end pt-2">
              <button
                onClick={() => setSelectedReport(null)}
                className="rounded-lg bg-slate-800 px-5 py-2 text-xs font-semibold text-slate-200 hover:bg-slate-700"
              >
                Close View
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
